### ISSUE TITLE
Parse Failing with special edit descriptor $

### ISSUE THREAD

**Issue by qcrist** [OpenFortranProject/ofp-sdf#38]
```
PROGRAM EX2
100   FORMAT(' ENTER NAME OF OUTPUT VERSION OF ''THERMAL'' TAPE: ',$)
END
```

`unknown parse fail (file: ~, char: 36/'$', position: 3:69 [105/140])`

https://docs.oracle.com/cd/E19957-01/805-4939/z40007438836/index.html

**Comment by rasmussn** [comment]
Grammar fixed by adding '$' to ControlEditDesc in FortranObsolete.sdf.  I'm not sure this is actually obsolete but can't find it in current standard and certainly seems to be in Fortran 77.

**Comment by qcrist** [comment]
Great, Thanks!
