### ISSUE TITLE
Compiling ofp2fast.str failure because of CommonStmt

### ISSUE THREAD

**Issue by ktras** [OpenFortranProject/ofp-sdf#7]
In ofp2fast.str
under is-specification-part has the following:

 +>  ?CommonStmt(_, _, _, _)

But when trying to make in trans, gives following error:

[ strc | info ] Compiling 'ofp2fast.str'
[ strc | error ] in definition is-specification-part(0|0): constructor CommonStmt/4 not declared
    CommonStmt(_, _, _, _)

The CommonStmt line is now commented out.

**Comment by rasmussn** [comment]
This appears to have been an early issue that has been resolved in the FAST.rtg specification.  CommonStmt now has arity of 2 and has many tests in tests/rule-tests/pp so should be thoroughly tested.
