### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by rouson** [OpenFortranProject/ofp-sdf#9]
As of February 9, 2015, there have been 633 commits since [release 0.9.1](https://github.com/OpenFortranProject/ofp-sdf/releases/tag/v0.9.1) on September 8, 2014.  In order to add ofp-sdf as an automatically installed prerequisite in the [OpenCoarrays](https://github.com/sourceryinstitute/opencoarrays) installation script without also requiring OpenCoarrays users to install git, it would be very helpful to post a new release.  I've started [draft release notes](https://github.com/OpenFortranProject/ofp-sdf/releases/tag/untagged-a35037d148ed3dd06f7b).

Also, if the current state of ofp-sdf is considered sufficiently robust for other projects to make ofp-sdf a mandatory prerequisite, it would be great to designate the next release as 1.0.0 for whatever confidence that might inspire in users.

**Comment by rouson** [comment]
I corrected the link to the [draft release notes](https://github.com/OpenFortranProject/ofp-sdf/releases/tag/untagged-a35037d148ed3dd06f7b) in the above comment.

**Comment by mjsottile** [comment]
This makes sense.  I don't know if Craig sees these issues on GitHub (Hello craig?).  I believe it is solid enough to make a 1.0.0 release (it was probably solid enough a while ago actually...).

**Comment by zbeekman** [comment]
If you mention him by user name @rasmussn it might improve the chances that it forwards to email

**Comment by rouson** [comment]
It's probably reasonable to close this now that a [1.0.0 release milestone](https://github.com/OpenFortranProject/ofp-sdf/milestones/1.0.0%20release) has been created and populated with issues that should be addressed prior to release.
